# Generated by Django 2.1.2 on 2018-10-13 20:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Geez',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.CharField(max_length=128, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=128, verbose_name='Address 2')),
                ('state', models.CharField(max_length=2, verbose_name='State')),
                ('zip_code', models.CharField(max_length=5, verbose_name='Zip Code')),
                ('longitude', models.FloatField(editable=False)),
                ('latitude', models.FloatField(editable=False)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.", regex='^\\+?1?\\d{9,15}$')])),
                ('description', models.TextField()),
                ('created', models.DateField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ohgeez.Category')),
            ],
        ),
    ]
