# Generated by Django 2.1.2 on 2018-10-13 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohgeez', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geez',
            name='created',
        ),
        migrations.RemoveField(
            model_name='geez',
            name='updated',
        ),
    ]
