# Generated by Django 2.1.2 on 2018-10-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohgeez', '0003_auto_20181013_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
    ]
