# Generated by Django 2.1.2 on 2018-10-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohgeez', '0004_auto_20181013_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='city',
            field=models.CharField(max_length=30, verbose_name='City'),
        ),
    ]
